repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6 # v1.35.1
    hooks:
      - id: yamllint
        args:
          - -d
          - "{ extends: relaxed, rules: { line-length: disable, document-start: disable, comments: disable, truthy: {check-keys: false} } }"
          - .github/workflows/
          - terraform/public/
          - tests/fixtures/terraform/private/
        pass_filenames: false
        files: ^\.github/workflows/.*\.ya?ml$|^terraform/public/.*\.ya?ml$|^tests/fixtures/terraform/private/.*\.ya?ml$

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint
        args: [.github/workflows]
        pass_filenames: false
        files: ^\.github/workflows/.*\.ya?ml$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 996abf60411a8d954288ac9856aae7602b80cbda # v0.22.1
    hooks:
      - id: markdownlint-cli2
        args: ["**/*.md"]
        pass_filenames: false
        files: \.md$
